/* Generated By:JavaCC: Do not edit this line. SocialProtocolParserConstants.java */
package tr.edu.boun.cmpe.mas.akin.hammurabi.protocol.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SocialProtocolParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int APROP = 5;
  /** RegularExpression Id. */
  int MPROP = 6;
  /** RegularExpression Id. */
  int LOR = 7;
  /** RegularExpression Id. */
  int LAND = 8;
  /** RegularExpression Id. */
  int LPARAN = 9;
  /** RegularExpression Id. */
  int RPARAN = 10;
  /** RegularExpression Id. */
  int LSQBRA = 11;
  /** RegularExpression Id. */
  int RSQBRA = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int EVENT_LABEL = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Achieve\"",
    "\"Maintain\"",
    "\"|\"",
    "\"&\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<EVENT_LABEL>",
    "<NUMBER>",
  };

}
