/* Generated By:JavaCC: Do not edit this line. SocialProtocolParserConstants.java */
package tr.edu.boun.cmpe.mas.akin.hammurabi.protocol.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SocialProtocolParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROTOCOL = 5;
  /** RegularExpression Id. */
  int COMMIT = 6;
  /** RegularExpression Id. */
  int PROHIBIT = 7;
  /** RegularExpression Id. */
  int AUTHORIZE = 8;
  /** RegularExpression Id. */
  int APROP = 9;
  /** RegularExpression Id. */
  int MPROP = 10;
  /** RegularExpression Id. */
  int LOR = 11;
  /** RegularExpression Id. */
  int LAND = 12;
  /** RegularExpression Id. */
  int LPARAN = 13;
  /** RegularExpression Id. */
  int RPARAN = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int LSQBRA = 17;
  /** RegularExpression Id. */
  int RSQBRA = 18;
  /** RegularExpression Id. */
  int SEMICOL = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int LABEL = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Protocol\"",
    "\"Commit\"",
    "\"Prohibit\"",
    "\"Authorize\"",
    "\"Achieve\"",
    "\"Maintain\"",
    "\"|\"",
    "\"&\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "<LABEL>",
    "<NUMBER>",
  };

}
