/* Generated By:JavaCC: Do not edit this line. EventTraceParserConstants.java */
package tr.edu.boun.cmpe.mas.akin.hammurabi.event.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EventTraceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int EVENT_LABEL = 7;
  /** RegularExpression Id. */
  int NUM = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\",\"",
    "<EVENT_LABEL>",
    "<NUM>",
  };

}
